
### Login Aprendiz
POST http://localhost:8000/
Content-Type: application/json

{
    "email":"juan@gmail.com",
    "password":"12345",
    "tipo":"aprendiz"
}

### Asistencia
 GET  http://localhost:8000/asistencia
Content-Type: application/json



