GET http://localhost:8000/fichas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0NzgwMjM0fQ.hvyO2NGkmM-Z5UIc_-Hgy5mOFPkqx5N1tD5hlM5eVZU
### 
GET http://localhost:8000/asistencia/tipos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0NzgwMjM0fQ.hvyO2NGkmM-Z5UIc_-Hgy5mOFPkqx5N1tD5hlM5eVZU