GET http://localhost:8000/fichas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0NzgwMjM0fQ.hvyO2NGkmM-Z5UIc_-Hgy5mOFPkqx5N1tD5hlM5eVZU

### 
GET http://localhost:8000/asistencia/tipos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0ODYyNjc5fQ.04ocVL0y2scESvsWH0qOsDAXe8-rHKurKl0b8maEB2s

###
GET http://localhost:8000/aprendices/ficha/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIENpcGFnYXV0YSBBcmJlbMOhZXoiLCJleHAiOjE3NDUyNTQxODh9.5fGUXAYCi40TJ9N3I7VtL8IEajs95ecGynzNkBVXZMI

###
GET http://localhost:8000/fichas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhYWEiLCJleHAiOjE3NDUyMDU1MDB9.lTmnitQ9wG5TePxzxRwkH8NDrQT9CM3gpH5kO3EVw7s
