GET http://localhost:8000/fichas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0NzgwMjM0fQ.hvyO2NGkmM-Z5UIc_-Hgy5mOFPkqx5N1tD5hlM5eVZU

### 
GET http://localhost:8000/asistencia/tipos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIiwiZXhwIjoxNzQ0ODYyNjc5fQ.04ocVL0y2scESvsWH0qOsDAXe8-rHKurKl0b8maEB2s

###
GET http://localhost:8000/aprendices/ficha/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJNYXJjbyBBbnRvbmlvIENpcGFnYXV0YSBBcmJlbMOhZXoiLCJleHAiOjE3NDUyNTQxODh9.5fGUXAYCi40TJ9N3I7VtL8IEajs95ecGynzNkBVXZMI

###
GET http://localhost:8000/fichas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhZmRhZmFzIGFkZmFkZmFzZGYiLCJleHAiOjE3NDU2MTYxNzl9.FB0TDU2Wj_5acLBxYFc3mAbekn9Q-CKdO1s9Gs_TS9o

###
GET http://localhost:8000/fichas/instructor/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhZmRhZmFzIGFkZmFkZmFzZGYiLCJleHAiOjE3NDU2MTYxNzl9.FB0TDU2Wj_5acLBxYFc3mAbekn9Q-CKdO1s9Gs_TS9o

###
@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJhZmRhZmFzIGFkZmFkZmFzZGYiLCJleHAiOjE3NDU2MTYxNzl9.FB0TDU2Wj_5acLBxYFc3mAbekn9Q-CKdO1s9Gs_TS9o

GET {{baseUrl}}/fichas/instructor/1
Content-Type: application/json
Authorization: Bearer {{token}}



